### ISSUE TITLE
Light edits to intro slides

### ISSUE THREAD

**Issue by tyleransom** [jmxpearson/duke-julia-ssri-2016#1]
@jmxpearson Some suggested light edits to `intro_slides.ipynb`, if you have time:

1. "Serious Julia user for ..." --> add 1 year to each of our numbers 
2. "Currently 0.4.3, soon to be 0.5, with very active developer community (more later)" --> "Currently 0.5.1, soon to be 0.6, with very active developer community (more later)"
3. "[julia-users list](https://groups.google.com/forum/#!forum/julia-users)" --> [Julia discourse](https://discourse.julialang.org/)
4. "v0.5 should have an official release soon. Some big (breaking) changes from 0.4 to 0.5, so read up before switching." --> "v0.6 should have an official release soon. Some big (breaking) changes from 0.5 to 0.6, so read up before switching."

**Comment by jmxpearson** [comment]
Thanks!
